const ErrorCodes = {
  SUCCESS: "SUCCESS",
  COMMON_INVALID_PARAM: "COMMON_INVALID_PARAM",
  COMMON_DUPLICATE_REQUEST: "COMMON_DUPLICATE_REQUEST",
  COMMON_SYSTEM_ERROR: "COMMON_SYSTEM_ERROR",
  AUTH_LOGIN_REQUIRED: "AUTH_LOGIN_REQUIRED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  GROUP_NOT_STARTED: "GROUP_NOT_STARTED",
  GROUP_ARCHIVED: "GROUP_ARCHIVED",
  GROUP_DISSOLVED: "GROUP_DISSOLVED",
  GROUP_FULL: "GROUP_FULL",
  GROUP_INVITE_INVALID: "GROUP_INVITE_INVALID",
  MEMBER_NOT_ACTIVE: "MEMBER_NOT_ACTIVE",
  MEMBER_CREATOR_TRANSFER_REQUIRED: "MEMBER_CREATOR_TRANSFER_REQUIRED",
  TARGET_REQUIRED: "TARGET_REQUIRED",
  TARGET_LOCKED: "TARGET_LOCKED",
  TARGET_INVALID_VALUE: "TARGET_INVALID_VALUE",
  TARGET_INVALID_COIN: "TARGET_INVALID_COIN",
  CHECKIN_INVALID_METRICS: "CHECKIN_INVALID_METRICS",
  CHECKIN_LIMIT_REACHED: "CHECKIN_LIMIT_REACHED",
  CHECKIN_EDIT_EXPIRED: "CHECKIN_EDIT_EXPIRED",
  MAKEUP_USE_CHECKIN_TODAY: "MAKEUP_USE_CHECKIN_TODAY",
  MAKEUP_DATE_OUT_OF_RANGE: "MAKEUP_DATE_OUT_OF_RANGE",
  MAKEUP_DAILY_LIMIT_REACHED: "MAKEUP_DAILY_LIMIT_REACHED",
  PHOTO_COUNT_INVALID: "PHOTO_COUNT_INVALID",
  PHOTO_TYPE_INVALID: "PHOTO_TYPE_INVALID",
  PHOTO_UPLOAD_FAILED: "PHOTO_UPLOAD_FAILED",
  PHOTO_LOAD_FAILED: "PHOTO_LOAD_FAILED",
  REMARK_TOO_LONG: "REMARK_TOO_LONG",
  STATS_TARGET_UNSET: "STATS_TARGET_UNSET",
  STATS_NO_ACTIVE_MEMBER: "STATS_NO_ACTIVE_MEMBER",
  ARCHIVE_NOT_FOUND: "ARCHIVE_NOT_FOUND",
  SYSTEM_NOT_IMPLEMENTED: "SYSTEM_NOT_IMPLEMENTED"
};

const ErrorMessages = {
  SUCCESS: "操作成功",
  COMMON_INVALID_PARAM: "请求参数无效。",
  COMMON_DUPLICATE_REQUEST: "请求处理中，请勿重复提交。",
  COMMON_SYSTEM_ERROR: "系统异常，请稍后重试。",
  AUTH_LOGIN_REQUIRED: "请先登录后继续。",
  AUTH_FORBIDDEN: "无权限查看。",
  GROUP_NOT_STARTED: "小组尚未开始，暂不能打卡或补卡。",
  GROUP_ARCHIVED: "归档小组仅可查看。",
  GROUP_DISSOLVED: "小组已解散。",
  GROUP_FULL: "小组人数已满。",
  GROUP_INVITE_INVALID: "邀请码无效。",
  MEMBER_NOT_ACTIVE: "你已不属于该小组。",
  MEMBER_CREATOR_TRANSFER_REQUIRED: "请先转让创建者身份。",
  TARGET_REQUIRED: "请先设置目标。",
  TARGET_LOCKED: "目标已锁定。",
  TARGET_INVALID_VALUE: "请输入有效目标值。",
  TARGET_INVALID_COIN: "请输入有效一点币值。",
  CHECKIN_INVALID_METRICS: "请输入有效运动数据。",
  CHECKIN_LIMIT_REACHED: "该运动日期已达到 5 次有效打卡上限。",
  CHECKIN_EDIT_EXPIRED: "仅可在提交当天修改。",
  MAKEUP_USE_CHECKIN_TODAY: "今日运动请使用打卡。",
  MAKEUP_DATE_OUT_OF_RANGE: "只能补昨日或前天的卡。",
  MAKEUP_DAILY_LIMIT_REACHED: "今日补卡次数已用完。",
  PHOTO_COUNT_INVALID: "请上传 1 至 3 张运动照片。",
  PHOTO_TYPE_INVALID: "仅支持上传静态运动照片。",
  PHOTO_UPLOAD_FAILED: "运动照片上传失败，请重试。",
  PHOTO_LOAD_FAILED: "照片加载失败，请重试。",
  REMARK_TOO_LONG: "备注最多 100 字。",
  STATS_TARGET_UNSET: "未设置目标。",
  STATS_NO_ACTIVE_MEMBER: "暂无有效成员。",
  ARCHIVE_NOT_FOUND: "暂无可查看归档。",
  SYSTEM_NOT_IMPLEMENTED: "功能尚未实现。"
};

class AppError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = "AppError";
    this.code = code;
    this.details = details;
  }
}

function notImplemented(actionName) {
  return new AppError(
    ErrorCodes.SYSTEM_NOT_IMPLEMENTED,
    `${actionName} is reserved for a later implementation task.`
  );
}

module.exports = {
  AppError,
  ErrorCodes,
  ErrorMessages,
  notImplemented
};
